
import { AuthContextProvider } from "./context/auth";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
        <AuthContextProvider>
          
          {children}
        </AuthContextProvider>
      
      </body>
    </html>
  )
}
